<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "laundry_web_app"
 *
 * Auto generated by Extension Builder 2020-02-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'LaundryWeb App',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Sangram Bhavar, Rajveer Sahney, Danish Umair Ahmad, Sukanta Maity',
    'author_email' => 'sangram.bhavar@hof-university.de, rajveer.sahney@hof-university.de, danish.umair.ahmad@hof-university.de, sukanta.maity@hof-university.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
